name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Test project in native environment
        run: pio test -e native

      - name: Build console application
        run: pio run -e native

      - name: Build 'target' cross application
        run: pio run -e target
        
      - name: Build 'gun' cross application
        run: pio run -e gun

      - name: Archive test console application
        uses: actions/upload-artifact@v3
        with:
          name: consoleApp
          path: ./.pio/build/native/program

      - name: Archive targets host application
        uses: actions/upload-artifact@v3
        with:
          name: target.hex
          path: .pio/build/target/firmware.hex

      - name: Archive gun application
        uses: actions/upload-artifact@v3
        with:
          name: gun.hex
          path: .pio/build/gun/firmware.hex